post https://ealbomfsk2.execute-api.us-east-1.amazonaws.com/dev/appointment
Content-Type: application/json

{
  "slotId": 22222,
  "patientId": 485,
  "date": "2024-06-01",
  "countryISO": "MX"
}

### external
post https://ealbomfsk2.execute-api.us-east-1.amazonaws.com/dev/external
Content-Type: application/json

{
  "slotId": 33333,
  "patientId": 485,
  "date": "2024-06-01",
  "countryISO": "MX"
}
